# Generated by Django 4.2.3 on 2023-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='editorial',
            fields=[
                ('idcareer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='editorial/')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
