# Generated by Django 4.2.3 on 2023-07-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_career_delete_editorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idcourse', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('hour', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
